In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("cleaned-data.csv")
print("Success")

Success

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41176 entries, 0 to 41175
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   41176 non-null  int64
 1   job                   41176 non-null  object
 2   marital               41176 non-null  object
 3   education             41176 non-null  object
 4   default               41176 non-null  object
 5   housing               41176 non-null  object
 6   loan                  41176 non-null  object
 7   contact               41176 non-null  object
 8   month                 41176 non-null  object
 9   day_of_week           41176 non-null  object
 10  campaign              41176 non-null  int64
 11  pdays                 41176 non-null  int64
 12  previous              41176 non-null  int64
 13  poutcome              41176 non-null  object
 14  emp.var.rate          41176 non-null  float64
 15  cons.price.idx        41176 non-null  float64
 16  cons.conf.idx         41176 non-null  float64
 17  euribor3m             41176 non-null  float64
 18  nr.employed           41176 non-null  float64
 19  y                     41176 non-null  int64
 20  previously_contacted  41176 non-null  int64
dtypes: float64(5), int64(6), object(10)
memory usage: 6.6+ MB

In [5]:
df.isnull().sum()

age                     0
job                     0
marital                 0
education               0
default                 0
housing                 0
loan                    0
contact                 0
month                   0
day_of_week             0
campaign                0
pdays                   0
previous                0
poutcome                0
emp.var.rate            0
cons.price.idx          0
cons.conf.idx           0
euribor3m               0
nr.employed             0
y                       0
previously_contacted    0
dtype: int64

In [7]:
df.isnull().sum().sum()

np.int64(0)

In [9]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,previously_contacted
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0,0
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0,0
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0,0
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0,0
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0,0

In [10]:
df.tail()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,previously_contacted
41171,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,-1,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,1,0
41172,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,-1,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,0,0
41173,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,-1,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,0,0
41174,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,-1,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,1,0
41175,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,-1,1,failure,-1.1,94.767,-50.8,1.028,4963.6,0,0

In [11]:
df.describe()

,age,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,previously_contacted
count,41176.00000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000,41176.000000
mean,40.02380,2.567879,-0.741913,0.173013,0.081922,93.575720,-40.502863,3.621293,5167.034870,0.112663,0.036793
std,10.42068,2.770318,1.510540,0.494964,1.570883,0.578839,4.627860,1.734437,72.251364,0.316184,0.188256
min,17.00000,1.000000,-1.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000,0.000000,0.000000
25%,32.00000,1.000000,-1.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000,0.000000,0.000000
50%,38.00000,2.000000,-1.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000,0.000000,0.000000
75%,47.00000,3.000000,-1.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000,0.000000,0.000000
max,98.00000,56.000000,27.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000,1.000000,1.000000

In [13]:
X = df.drop("y", axis=1)
y = df["y"]

#### encoding or tarnsforming

In [20]:
X = pd.get_dummies(X, drop_first=True)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [23]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced"
)

In [24]:
model.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [25]:
print(X.dtypes)

age                                int64
campaign                           int64
pdays                              int64
previous                           int64
emp.var.rate                     float64
cons.price.idx                   float64
cons.conf.idx                    float64
euribor3m                        float64
nr.employed                      float64
previously_contacted               int64
job_blue-collar                     bool
job_entrepreneur                    bool
job_housemaid                       bool
job_management                      bool
job_retired                         bool
job_self-employed                   bool
job_services                        bool
job_student                         bool
job_technician                      bool
job_unemployed                      bool
job_unknown                         bool
marital_married                     bool
marital_single                      bool
marital_unknown                     bool
education_basic.6y                  bool
education_basic.9y                  bool
education_high.school               bool
education_illiterate                bool
education_professional.course       bool
education_university.degree         bool
education_unknown                   bool
default_unknown                     bool
default_yes                         bool
housing_unknown                     bool
housing_yes                         bool
loan_unknown                        bool
loan_yes                            bool
contact_telephone                   bool
month_aug                           bool
month_dec                           bool
month_jul                           bool
month_jun                           bool
month_mar                           bool
month_may                           bool
month_nov                           bool
month_oct                           bool
month_sep                           bool
day_of_week_mon                     bool
day_of_week_thu                     bool
day_of_week_tue                     bool
day_of_week_wed                     bool
poutcome_nonexistent                bool
poutcome_success                    bool
dtype: object

In [27]:
y_pred = model.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print(accuracy)

0.8936376881981545

In [29]:
prediction = model.predict(X.iloc[[3]])
print(prediction)

[0]

In [33]:
prediction = model.predict(X.iloc[[9]])
print(prediction)

[0]

In [30]:
print(df["y"].unique())

[0 1]

In [31]:
df["y"].unique()

array([0, 1])